version: '3.9'
services:
  db_quiz:
    container_name: db_quiz
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env
    ports:
      - '5432:5432'

volumes:
  db_data: